question_answer/auth/urls.py
from django.conf.urls import patterns, include, url

from .views import SignUpView, LoginView, LogoutView


urlpatterns = patterns('',
    url(r'^accounts/register/$', SignUpView.as_view(), name='signup'),
    url(r'^accounts/login/$', LoginView.as_view(), name='login'),
    url(r'^accounts/logout/$', LogoutView.as_view(), name='logout'),
)

question_answer/qat/urls.py
from django.conf.urls import patterns, include, url

from .views import (HomePageView,
   CardListView, CardDetailView,
   AskListView,AskDetailView,
   AnswerListView, AnswerDetailView)


answer_patterns = patterns(
    '',
    url(r'^d/(?P<pk>\d+)/$', AnswerDetailView.as_view(), name='detail'),
    url(r'^l$', AnswerListView.as_view(), name='list'),
    url(r'^l$', AnswerListView.as_view(), name='create'),
    url(r'^d/(?P<pk>\d+)/$', AnswerDetailView.as_view(), name='update'),
    url(r'^d/(?P<pk>\d+)/$', AnswerDetailView.as_view(), name='delete'),
)


asks_patterns = patterns(
    '',
    url(r'^d/(?P<pk>\d+)/', AskDetailView.as_view(), name='detail'),
    url(r'^l$', AskListView.as_view(), name='list'),
    url(r'^l$', AskListView.as_view(), name='create'),
    url(r'^d/(?P<pk>\d+)/', AskDetailView.as_view(), name='update'),
    url(r'^d/(?P<pk>\d+)/', AskDetailView.as_view(), name='delete'),
)


cards_patterns = patterns(
    '',
    url(r'^d/(?P<pk>\d+)/$', CardDetailView.as_view(), name='detail'),
    url(r'^l$', CardListView.as_view(), name='list'),
    url(r'^l$', CardListView.as_view(), name='create'),
    url(r'^d/(?P<pk>\d+)/$', CardDetailView.as_view(), name='update'),
    url(r'^d/(?P<pk>\d+)/$', CardDetailView.as_view(), name='delete'),
)


urlpatterns = patterns('',
    url(r'^home$', HomePageView.as_view(), name='home'),
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^answer/', include(answer_patterns, namespace='answer')),
    url(r'^ask/', include(asks_patterns, namespace='ask')),
    url(r'^', include(cards_patterns, namespace='card')),
)

question_answer/question_answer/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

import qat

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'question_answer.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('qat.urls', namespace='qat',)),
    url(r'^', include('auth.urls', namespace='auth',)),
)

question_answer/qat/models.py
from django.core.urlresolvers import reverse
from django.db import models


class Answer(models.Model):
    answer = models.CharField(max_length=10000)
    correctly = models.BooleanField(default=False)

    def __str__(self):
        return self.answer[:50]

    def get_absolute_url(self):
        return reverse('qat:answer:detail', kwargs={'pk': self.pk})


class Ask(models.Model):
    ask = models.CharField(max_length=10000)
    answer1 = models.OneToOneField(Answer, related_name='answer1')
    answer2 = models.OneToOneField(Answer, related_name='answer2')
    answer3 = models.OneToOneField(Answer, related_name='answer3')
    answer4 = models.OneToOneField(Answer, related_name='answer4')
    answer5 = models.OneToOneField(Answer, related_name='answer5')

    def __str__(self):
        return self.ask[:50]

    def get_absolute_url(self):
        return reverse('qat:ask:detail', kwargs={'pk': self.pk})

    def get_answer1(self):
        return reverse('qat:answer:detail', kwargs={'pk': self.answer1.pk})

    def separator(self):
        return "="*66

    def get_next_url(self):
        try:
            return reverse('qat:ask:detail', kwargs={'pk': self.pk+1})
        except:
            return reverse('qat:ask:detail', kwargs={'pk': self.pk})

    def get_prev_url(self):
        try:
            return reverse('qat:ask:detail', kwargs={'pk': self.pk-1})
        except:
            return reverse('qat:ask:detail', kwargs={'pk': self.pk})


class Card(models.Model):
    nomer = models.IntegerField()
    ask1 = models.OneToOneField(Ask, related_name='ask1')
    ask2 = models.OneToOneField(Ask, related_name='ask2')
    ask3 = models.OneToOneField(Ask, related_name='ask3')
    ask4 = models.OneToOneField(Ask, related_name='ask4')
    ask5 = models.OneToOneField(Ask, related_name='ask5')
    ask6 = models.OneToOneField(Ask, related_name='ask6')
    ask7 = models.OneToOneField(Ask, related_name='ask7')
    ask8 = models.OneToOneField(Ask, related_name='ask8')
    ask9 = models.OneToOneField(Ask, related_name='ask9')

    def __str__(self):
        return "".join(["card ", str(self.nomer)])

    def get_absolute_url(self):
        return reverse('qat:card:detail', kwargs={'pk': self.pk})

question_answer/qat/views.py
from django.views import generic
from django.core.urlresolvers import reverse_lazy

from . import models




class HomePageView(generic.RedirectView):
    url = reverse_lazy('qat:card:list')


class AnswerListView(generic.ListView):
    model = models.Answer


# class LogoutView(generic.RedirectView):
#     url = reverse_lazy('home')
#
#     def get(self, request, *args, **kwargs):
#         logout(request)
#         return super(LogoutView, self).get(request, *args, **kwargs)



class AnswerDetailView(generic.DetailView):
    model = models.Answer

    def get_queryset(self):
        queryset = super(AnswerDetailView, self).get_queryset()
        # queryset = queryset | models.Ask.objects.filter(id=self.request.user)
        return queryset


class AskListView(generic.ListView):
    model = models.Ask


class AskDetailView(generic.DetailView):
    model = models.Ask


class CardListView(generic.ListView):
    model = models.Card


class CardDetailView(generic.DetailView):
    model = models.Card

question_answer/qat/templates/qat/answer_detail.html
{% extends '_layouts/base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ object.name }} | Lists | {{ block.super }}{% endblock title %}

{% block headline %}
<h1>{{ object.answer }}</h1>
{% endblock headline %}

{% block content %}
<style>
    .answer_hide {background: black;}
    .answer_true {background: #1AF029;}
    .answer_false {background: #F5111D;}
</style>
<div class="row">
    <div class="col-sm-12">
        <p {% if object.correctly %}class="answer_true"
            {% else %}class="answer_false"{% endif %}>
            <a href="{% url 'qat:answer:detail' object.pk %}"></a>
            {{ object.answer }}</p>
    </div>
</div>
<div class="row">
    <br><hr>
    <div class="col-sm-6">
        <p><a href="{% url 'qat:ask:list' %}">Back to lists asks</a></p>
        <p><a href="{% url 'qat:card:list' %}">Back to lists cards</a></p>
    </div>
</div>
{% endblock %}

question_answer/qat/templates/qat/ask_detail.html
{% extends '_layouts/base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ object.name }} | Lists | {{ block.super }}{% endblock title %}

{% block headline %}
<h3>{{ object.ask }}</h3><hr>
{% endblock headline %}

{% block content %}
<div class="row">
    <div id="answers" class="col-xs-12">
        <p id="choice1" style="margin:1px;font-size:20px;" {% if object.answer1.correctly %} class="answer_true"
            {% else %}class="answer_false"{% endif %}>
            <a href="#"></a>
            1) {{ object.answer1.answer }}</p>
        <p id="choice2" style="margin:1px;padding:0px;font-size:20px;" {% if object.answer2.correctly %}class="answer_true"
            {% else %}class="answer_false"{% endif %}>
            <a href="#"></a>
            2) {{ object.answer2.answer }}</p>
        <p id="choice3" style="margin:1px;font-size:20px;" {% if object.answer3.correctly %}class="answer_true"
            {% else %}class="answer_false"{% endif %}>
            <a href="#"></a>
            3) {{ object.answer3.answer }}</p>
        <p id="choice4" style="margin:1px;font-size:20px;" {% if object.answer4.correctly %}class="answer_true"
            {% else %}class="answer_false"{% endif %}>
            <a href="#"></a>
            4) {{ object.answer4.answer }}</p>
        <p id="choice5" style="margin:1px;font-size:20px;" {% if object.answer5.correctly %}class="answer_true"
            {% else %}class="answer_false"{% endif %}>
            <a href="#"></a>
            5) {{ object.answer5.answer }}</p>
        <hr>
    </div>
</div>
<div class="row">
    <br><hr>
    <div class="col-sm-6">
        <p ><a id="prev" href="{{ object.get_prev_url }}">Предыдущий (q)</a></p>
        <p ><a id="next" href="{{ object.get_next_url }}">Следующий (w)</a></p>
        <br><hr>
        <p><a href="{% url 'qat:ask:list' %}">Вернуться к списку вопросов</a></p>
        <p><a href="{% url 'qat:card:list' %}">Вернуться к списку билетов</a></p>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
    $('#answers>p').unbind();

    $('#answers').find('>p').on('click', function() {
      if ($(this).hasClass('answer_true')) {
        $(this).css("background", "#1AF029");
      }
      if ($(this).hasClass('answer_false')) {
        return $(this).css("background", "#F5111D");
      }
    });

    $('body').bind('keypress', function(e) {
        if(e.keyCode == 49){$('#choice1').trigger("click");}
        if(e.keyCode == 50){$('#choice2').trigger("click")}
        if(e.keyCode == 51){$('#choice3').trigger("click")}
        if(e.keyCode == 52){$('#choice4').trigger("click")}
        if(e.keyCode == 53){$('#choice5').trigger("click")}
        if(e.keyCode == 113){
            var href = $('#prev').attr('href');
            window.location.href = href; //causes the browser to refresh and load the requested url
            $('#prev').trigger("click");
        }
        if(e.keyCode == 119){
            var href = $('#next').attr('href');
            window.location.href = href; //causes the browser to refresh and load the requested url
            $('#next').trigger("click");
        }
    });
</script>
{% endblock js %}

question_answer/qat/templates/qat/ask_list.html
<html>
<head>
    <style>
      body {
        /*width: 980px;*/
        word-break: break-all;
        word-wrap: break-word;
        font-size: 20px;
      }
      ul {
        margin: 0px;
        padding: 0px;
      }
      a {
        text-decoration: none;
        color: black;
      }
    </style>
</head>
<body>
<ul class="list-group" style="list-style-type: none;">
    {% for object in object_list %}
    <li class="list-group-item">
        <a href="{{ object.get_absolute_url }}">$
          {% if object.ask1.nomer %}{{ object.ask1.nomer }}/1{% endif %}
          {% if object.ask2.nomer %}{{ object.ask2.nomer }}/2{% endif %}
          {% if object.ask3.nomer %}{{ object.ask3.nomer }}/3{% endif %}
          {% if object.ask4.nomer %}{{ object.ask4.nomer }}/4{% endif %}
          {% if object.ask5.nomer %}{{ object.ask5.nomer }}/5{% endif %}
          {% if object.ask6.nomer %}{{ object.ask6.nomer }}/6{% endif %}
          {% if object.ask7.nomer %}{{ object.ask7.nomer }}/7{% endif %}
          {% if object.ask8.nomer %}{{ object.ask8.nomer }}/8{% endif %}
          {% if object.ask9.nomer %}{{ object.ask9.nomer }}/9{% endif %}
           - {{ object.ask }} </a>
    </li>
    <li class="list-group-item">
        <a href="{{ object.get_answer1 }}">
        {% if object.answer1.correctly %}@ {% else %}# {% endif %}
        1- {{ object.answer1.answer }}</a>
    </li>
    <li class="list-group-item">
        <a href="{{ object.get_answer2 }}">
        {% if object.answer2.correctly %}@ {% else %}# {% endif %}
        2- {{ object.answer2.answer }}</a>
    </li>
    <li class="list-group-item">
        <a href="{{ object.get_answer3 }}">
        {% if object.answer3.correctly %}@ {% else %}# {% endif %}
        3- {{ object.answer3.answer }}</a>
    </li>
    <li class="list-group-item">
        <a href="{{ object.get_answer4 }}">
        {% if object.answer4.correctly %}@ {% else %}# {% endif %}
        4- {{ object.answer4.answer }}</a>
    </li>
    <li class="list-group-item">
        <a href="{{ object.get_answer5 }}">
        {% if object.answer5.correctly %}@ {% else %}# {% endif %}
        5- {{ object.answer5.answer }}</a>
    </li>
    <li>{{ object.separator }}</li>
    {% empty %}
    <li class="list-group-item">You have no lists</li>
    {% endfor %}
</ul>

</body>
</html>

question_answer/qat/templates/qat/card_detail.html
{% extends '_layouts/base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ object.name }} | Lists | {{ block.super }}{% endblock title %}

{% block headline %}
<h1>{{ object.nomer }}</h1>
{% endblock headline %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <p><a href="{% url 'qat:ask:detail' object.ask1.pk %}">1) {{ object.ask1.ask }}</a></p>
        <p><a href="{% url 'qat:ask:detail' object.ask2.pk %}">2) {{ object.ask2.ask }}</a></p>
        <p><a href="{% url 'qat:ask:detail' object.ask3.pk %}">3) {{ object.ask3.ask }}</a></p>
        <p><a href="{% url 'qat:ask:detail' object.ask4.pk %}">4) {{ object.ask4.ask }}</a></p>
        <p><a href="{% url 'qat:ask:detail' object.ask5.pk %}">5) {{ object.ask5.ask }}</a></p>
        <p><a href="{% url 'qat:ask:detail' object.ask6.pk %}">6) {{ object.ask6.ask }}</a></p>
        <p><a href="{% url 'qat:ask:detail' object.ask7.pk %}">7) {{ object.ask7.ask }}</a></p>
        <p><a href="{% url 'qat:ask:detail' object.ask8.pk %}">8) {{ object.ask8.ask }}</a></p>
        <p><a href="{% url 'qat:ask:detail' object.ask9.pk %}">9) {{ object.ask9.ask }}</a></p>
    </div>
</div>
<div class="row">
    <br><hr>
    <div class="col-sm-6">
        <p><a href="{% url 'qat:card:list' %}">Вернуться к списку билетов</a></p>
    </div>
</div>
{% endblock %}

question_answer/qat/templates/qat/card_list.html
{% extends '_layouts/base.html' %}

{% block title %}Lists | {{ block.super }}{% endblock title %}

{% block headline %}<h1>Список билетов</h1>{% endblock headline %}

{% block content %}
<div class="row">
    <div class="col-sm-6">
        <ul class="list-group">
            {% for object in object_list %}
            <li class="list-group-item">
                <a href="{{ object.get_absolute_url }}">Билет N{{ object.nomer }}</a>
            </li>
            {% empty %}
            <li class="list-group-item">You have no lists</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

question_answer/templates/_layouts/base.html
<!DOCTYPE>
<html>
<head>
    <title>{% block title %}Проверка знаний по электробезопасности{% endblock title %}</title>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <style>
        body {
            padding-bottom: 20px;
            padding-top: 70px;
        }
        .messages {
            list-style: none;
        }
    </style>
    {% block css %}{% endblock css %}
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Проверка знаний по электробезопасности</a>
        </div>
          <div class="navbar-collapse collapse">
              {% if not user.is_authenticated %}
              <a href="{% url 'auth:signup' %}" class="btn btn-default navbar-btn">Регистрация</a>
              <a href="{% url 'auth:login' %}" class="btn btn-default navbar-btn">Войти</a>
              {% else %}
              <a href="{% url 'auth:logout' %}" class="btn btn-default navbar-btn">Выход</a>
              {% endif %}
          </div><!--/.navbar-collapse -->
      </div>
    </div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="container">
        <div class="container">{% block headline %}{% endblock headline %}</div>
    </div>
    <div class="container">
        {% block content %}{% endblock content %}
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    {% block js %}
    {% endblock js %}
</body>
</html>

question_answer/templates/accounts/login.html
{% extends '_layouts/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Login | {{ block.super }}{% endblock %}

{% block headline %}<h1>Войти</h1>{% endblock %}

{% block content %}
{% crispy form %}
{% endblock content %}

question_answer/templates/accounts/signup.html
{% extends '_layouts/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Register | {{ block.super }}{% endblock %}

{% block headline %}<h1>Регистрация</h1>{% endblock %}

{% block content %}
{% crispy form %}
{% endblock content %}

question_answer/templates/home.html
{% extends '_layouts/base.html' %}
{% block headline %}<h1>Электробезопасность</h1>
{% endblock %}


{% block content %}
<p>{% if user.is_authenticated %} Вы вошли как: {{user.username }}
{% else %}{% endif %}
</p>

{% endblock content %}